server:
  port: 7111

spring:
  application:
    name: tasky_manager

  datasource:
    url: jdbc:postgresql://db-postgresql-nyc3-68435-do-user-13333067-0.g.db.ondigitalocean.com:25060/taskyy_dev
    username: "titusdb"
    password: "AVNS_eJdCUVeiRqaPxSMhgxq"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

authentication:
  signing-key: 'test_test'
  jwt-expiration-time: 9999999
